### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by hkhosrav** [hkhosrav/RiPLE-Client-side#4]
Create a Badge view for the project

**Comment by CaptainAchilles** [comment]
Badge structure:
```
{
    id: number,
    name: string
}
```

Badge Acquisition Structure:
```
{
    badgeId: number,
    dateAquired: date,
}
```

**Comment by hkhosrav** [comment]
Maybe

Badge structure:

{
    id: number,
    type: number, (e.g. engagement, competency, social)
    name: string
}
Badge Acquisition Structure:

{
    badgeId: number,
    Acquired: bool, 
    dateAquired: date
}

**Comment by CaptainAchilles** [comment]
I like the idea of a badge type, it's a good thing to use for organisation in the client. 

If a user has a `BadgeAcquisition` then wouldn't they implicitly also have that badge? It seems redundant to store the badges a user doesn't have.

**Comment by hkhosrav** [comment]
I was thinking of maybe having a progress bar that shows how close a user is to acquiring a badge, so you might also want to store information about badges that have not been acquired yet. It comes down to the actual implementation I guess.

**Comment by solmazabdi** [comment]
I like the idea of having a progress bar and can have positive impact on
perceiving badge process.

**Comment by CaptainAchilles** [comment]
I have mocked up the following:
![image](https://user-images.githubusercontent.com/16090868/28097629-9ff67fbe-66f4-11e7-88fc-59c46bfa6f1f.png)

**Comment by hkhosrav** [comment]
Looks great!
