### ISSUE TITLE
Prototype Connections Page

### ISSUE THREAD

**Issue by hkhosrav** [hkhosrav/RiPLE-Client-side#5]
Part of this project is to allow users to grow their social connectedness. A prototype should be implemented to get a feel for this.

**Comment by solmazabdi** [comment]
![findfriends](https://user-images.githubusercontent.com/8370785/27017214-0cdd2004-4f3c-11e7-9576-8f69bc323ca5.jpg)
![peertutoring](https://user-images.githubusercontent.com/8370785/27017215-0ce11ac4-4f3c-11e7-9743-30b626ea720c.jpg)
![be a turor](https://user-images.githubusercontent.com/8370785/27017213-0cdae2da-4f3c-11e7-82e2-b73b200793ec.jpg)

**Comment by hkhosrav** [comment]
Good initial prototypes. Please update based on our in-person discussions.

**Comment by hkhosrav** [comment]
@solmazabdi can you summarise the outcomes and close the issue?

**Comment by solmazabdi** [comment]
"connect to peers" tab includes 2 main parts. In the first division, students determine their available time and the second division is dedicated to connecting to potential peers. This division includes 3 main tabs: provide mentorship, seek mentorship and find study partner. In each of these tabs students can determine the preferred topics and select peers from available cards that are presented. 
![image](https://user-images.githubusercontent.com/8370785/27315367-6b20526e-558e-11e7-8a3a-d78862a51502.png)
Each card includes different parts, including student's name, pic, a brief description, available time, and preferred topics. 
![card](https://user-images.githubusercontent.com/8370785/27315475-11f51c3c-558f-11e7-80ea-a3682ea84180.png)
